"""empty message

Revision ID: f6e723211c75
Revises: 49952fde9c90
Create Date: 2020-06-01 15:29:49.686567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e723211c75'
down_revision = '49952fde9c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan_versioning',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_eff_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_eff_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=30), nullable=False),
    sa.CheckConstraint('start_eff_date <= end_eff_date'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('activation_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'expiry_date')
    op.drop_column('subscriptions', 'activation_date')
    op.drop_table('subscription_plan_versioning')
    # ### end Alembic commands ###
